#!/usr/bin/env python3
"""Math tables for the renderer, emitted as a ca65 source file (LUT00 bank).

Fixed-point contracts (shared with src/render.s):
  world coords      s11.4 (16-bit signed, value = units * 16)
  angles            16-bit BAM, tables indexed by high byte
  sin/cos           s8.8 signed (+-256)
  rzh               524288 / z_units, clamped to 32767 (z < 16 clamps)
  projection        col = 16 + (hi16(tx_s114 * rzh) >> 3)   [FOV 90deg, 32 cols]
  wall height       hpx = 10240 / z  (=> 20 tiles at z = 64)
"""
import argparse
import math

CLASSES = [1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 20]


def byte_rows(vals):
    out = []
    for i in range(0, len(vals), 16):
        out.append("    .byte " + ", ".join(f"${v & 0xFF:02X}" for v in vals[i:i+16]))
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    sin_v = [round(256 * math.sin(i * 2 * math.pi / 256)) for i in range(256)]
    # clamp +256 -> +255*... keep 256: fits s16; hi/lo split handles it
    recipf = [32767 if z < 16 else min(32767, round(524288 / z)) for z in range(1024)]
    recip_col = [0] + [min(65535, 65536 // n) for n in range(1, 256)]

    # atan_tbl[i] = atan(i/256) in BAM high-byte units (256/circle), 0..32.
    # Used by atan2_hi: ratio = min * recipf[max>>4] >> 15 (division-free).
    atan_v = [round(math.atan(i / 256) * 256 / (2 * math.pi)) for i in range(256)]

    # angcol_tbl[a_rel + 36] = screen column of view-relative angle a_rel
    # (BAM hi units, CCW positive): col = 16 - 16*tan(a), clamped [0, 32].
    # 36 = frustum half-angle (32) + clip slack, matching PF_CLIP in render.s.
    angcol = []
    for i in range(73):
        a = (i - 36) * 2 * math.pi / 256
        angcol.append(max(0, min(32, round(16 - 16 * math.tan(a)))))

    hclass = []
    light = []
    light2 = []
    for i in range(256):
        rzh = i * 128 + 64
        tiles = rzh / 409.6
        cls = min(range(len(CLASSES)), key=lambda k: abs(CLASSES[k] - tiles))
        if tiles < 1:
            cls = 0
        hclass.append(cls)
        z = 524288 / rzh
        light.append(0 if z < 96 else 1 if z < 160 else 2 if z < 288 else 3)
        # double-resolution distance light: odd values are the half-band
        # transition zones, dithered by column parity at emit time
        light2.append(0 if z < 78 else 1 if z < 96 else 2 if z < 125 else
                      3 if z < 160 else 4 if z < 214 else 5 if z < 288 else 6)

    wtop = [(20 - h) // 2 for h in CLASSES]
    wbot = [(20 - h) // 2 + h for h in CLASSES]

    with open(args.out, "w") as f:
        f.write("; GENERATED by tools/tablegen.py — do not edit\n")
        f.write('.export sin_lo, sin_hi, recipf_lo, recipf_hi\n')
        f.write('.export recip_col_lo, recip_col_hi, hclass_tbl, light_tbl, light2_tbl\n')
        f.write('.export wtop_tbl, wbot_tbl, atan_tbl, angcol_tbl\n')
        f.write('.segment "LUT00"\n')
        for name, vals in (
            ("sin_lo", [v & 0xFF for v in sin_v]),
            ("sin_hi", [(v >> 8) & 0xFF for v in sin_v]),
            ("recipf_lo", [v & 0xFF for v in recipf]),
            ("recipf_hi", [v >> 8 for v in recipf]),
            ("recip_col_lo", [v & 0xFF for v in recip_col]),
            ("recip_col_hi", [v >> 8 for v in recip_col]),
            ("hclass_tbl", hclass),
            ("light_tbl", light),
            ("light2_tbl", light2),
            ("wtop_tbl", wtop),
            ("wbot_tbl", wbot),
            ("atan_tbl", atan_v),
            ("angcol_tbl", angcol),
        ):
            f.write(f"{name}:\n{byte_rows(vals)}\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
