; CHR-ROM payload (generated by tools/tilegen.py; ld65 pads the area to 1MB)
.segment "CHRDATA"
.ifdef M2DEMO
.incbin "assets/build/chr-test.bin"
.elseif .defined(FULL_E1M1)
.incbin "assets/build/chr-e1m1-full.bin"
.elseif .defined(E1M1)
.incbin "assets/build/chr-e1m1.bin"
.else
.incbin "assets/build/chr-game.bin"
.endif
